### ISSUE TITLE
Missing hash tables from git LFS?

### ISSUE THREAD

**Issue by Detry322** [AnonGit90210/RamanujanMachine#13]
Are the hashtables used to run the ramanujan machine part of this github repository? I can’t run the software without them.

**Comment by chriscow** [comment]
I found if you go into the config.ini and change the `hashtable_file_operation` setting to `generate` you can at least run the program if you just want to get it going. That should generate a hashtable for you to use.  Then change the setting back to `use` and run it again.  I'm just getting started also so hopefully this gets us going.

**Comment by AnonGit90210** [comment]
Hello,
Indeed, at the moment local generation of hashtable files is required. We're working on some infrastructure updates, after which we'll create large hashtables for general public use. We updated the default config.ini file to 'generate' instead of 'use', as we've seen it causes confusion (thanks for bringing this up).
You can either set 'gen_hashtable_only=false' to create the hashtable and start looking for hits right after, or (as I personally recommend) run it once again after the hashtable is created with 'use', as many times you want over different lhs parameters.
